# -*- coding: utf-8 -*-
"""Gradient MCI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A8fchi0OWqXHbjFh-N9KgWsnjQqTHWxN
"""

import numdifftools as nd


g=lambda x:(2*x**3)+(x**2)+3
grad1 = nd.Gradient(g)([1])
print("Gradient of 2*x ^3 + x^2 +3 at x=1 is",grad1)

def mg(x):
  
  return 2*(x[1])**3 + 4*x[0]*x[2] + 3*x[0]

grad2 = nd.Gradient(mg)([1,1,1])
print("Gradient of (2y^3) + 4xz + 3x at (1,1,1) is",grad2)

import numdifftools as nd


g=lambda x:(2*x**3)+(x**2)+3
grad1 = nd.Gradient(g)([1])
print("Gradient of 2*x ^3 + x^2 +3 at x=1 is",grad1)

def mg(x):
  
  return 2*(x[0])**2 + 3*x[1]**2 + x[2]**2

grad2 = nd.Gradient(mg)([1,1,1])
print("Gradient of (2x^2) + 2y^2 + z^2 at (1,1,1) is",grad2)