# -*- coding: utf-8 -*-
"""Gram Schmidt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rWGZdEVVBXJXMUvPimjujbksbkXAY5Pk
"""

import numpy as np
from numpy import *
from sympy import *

row=int(input("Enter The Number of Rows in Matrix:"))
col=int(input("Enter The Number of Columns in Matrix:"))

matrix=[]

for i in range(row):
  z=[]
  for j in range(col):
    z.append(float(input("Enter The Matrix Element:")))
  matrix.append(Matrix(z))

print(matrix)

a=GramSchmidt(matrix)
print(a)