# -*- coding: utf-8 -*-
"""Sahaj Khurana MCI Practical (Matrix).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ngAJgJPTY7Sfg_W1CtHXt4Ev7BIZMk3O
"""

import numpy as np , sympy

M1=np.matrix([[8,5,2],[3,3,1],[7,8,1]])
print("Matrix M1 is \n",M1)

a=sympy.Matrix([[8,5,2],[3,3,1],[7,8,1]]).rref()
print("The Row Echelon Form is",a)

rank_M1=sympy.Matrix([[8,5,2],[3,3,1],[7,8,1]]).rank()
print("The Rank Of Matrix is",rank_M1)

import numpy as np , sympy as sp
matrix=[]
row = int(input("Enter Number of Rows:"))
column = int(input("Enter Number of Columns:"))

for i in range(row):
  a=[]
  for j in range(column):
    a.append(int(input("Enter Element of Matrix:")))
  matrix.append(a)

for i in range(row):
  for j in range(column):
    print(matrix[i][j],end=" ")
  print()

a=sympy.Matrix(matrix).rref()
print("The Row Echelon Form is",a)